name: text_snd_prod
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_flavor: ^3.1.3
  flutter_flavorizr: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "テキストSNS Dev"
      android:
        applicationId: "com.firebase.text_sns_test"
      ios:
        bundleId: "com.firebase.textSnsTest"
    prod:
      app:
        name: "テキストSNS"
      android:
        applicationId: "com.firebase.text_snd_prod"
      ios:
        bundleId: "com.firebase.textSndProd"